# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selfie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('Person', ('Selfie', 'Nonselfie')), ('Other', 'other')], default='Other', max_length=10)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
